In [236]:
import pandas as pd

file_path = '../external-data/train.csv'

housing_df = pd.read_csv(file_path)

# check the size of data frame, x - rows number, y - columns number
housing_df.shape

(1460, 81)

In [237]:
housing_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [238]:
# pd.set_option('display.max_rows', 5) ???
# select SalePrice Series from data frame
sale_price_series1 = housing_df.SalePrice
sale_price_series1

0       208500
1       181500
         ...
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [239]:
# another way to select SalePrice Series from data frame
sale_price_series2 = housing_df['SalePrice']
sale_price_series2

0       208500
1       181500
         ...
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [240]:
# select single value from SalePrice Series
house0 = housing_df.SalePrice[0]
house0

np.int64(208500)

In [241]:
# select first 3 house prices using index-based approach, SalePrice is the last 81st column
housing_df.iloc[:3, 80]

0    208500
1    181500
2    223500
Name: SalePrice, dtype: int64

In [242]:
# select 2 house prices before the last in the list using index-based approach, SalePrice is the last 81st column
housing_df.iloc[1457:1459, 80]

1457    266500
1458    142125
Name: SalePrice, dtype: int64

In [243]:
# another way select 2 house prices before the last in the list using index-based approach, SalePrice is the last 81st column
housing_df.iloc[-3:-1, 80]

1457    266500
1458    142125
Name: SalePrice, dtype: int64

In [244]:
# select SalePrice, LotArea and YearBuilt of the last 3 houses using label-based selection
housing_df.loc[1457:, ['SalePrice', 'LotArea', 'YearBuilt']]

      SalePrice  LotArea  YearBuilt
1457     266500     9042       1941
1458     142125     9717       1950
1459     147500     9937       1965

In [245]:
# set index to the SalePrice
housing_df.set_index("SalePrice")

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
SalePrice,,,,,,,,,,,,,,,,,,,,,
208500,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
181500,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142125,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
147500,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal

In [246]:
# creating the Series of True/False values (==)
condition = housing_df.SaleCondition == 'Abnorml'

# select only the rows with True, SaleCondition is 'Abnorml', using loc
housing_df.loc[condition]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000
1453,1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500

In [247]:
# complex condition to select Abnormal with area smaller than 6200
complexCondition = (housing_df.SaleCondition == 'Abnorml') & (housing_df.LotArea < 6200)

# select the rows with this houses
housing_df.loc[complexCondition]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
56,57,160,FV,24.0,2645,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2009,WD,Abnorml,172500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1364,1365,160,FV,30.0,3180,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,144152
1449,1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000

In [248]:
# look for Abnormal or Partial
housing_df.loc[housing_df.SaleCondition.isin(['Abnormal', 'Partial'])]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1437,1438,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,New,Partial,394617
1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090

In [249]:
# look for houses with the pool
housing_df.loc[housing_df.PoolQC.notnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
197,198,75,RL,174.0,25419,Pave,NaN,Reg,Lvl,AllPub,...,512,Ex,GdPrv,NaN,0,3,2006,WD,Abnorml,235000
810,811,20,RL,78.0,10140,Pave,NaN,Reg,Lvl,AllPub,...,648,Fa,GdPrv,NaN,0,1,2006,WD,Normal,181000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1386,1387,60,RL,80.0,16692,Pave,NaN,IR1,Lvl,AllPub,...,519,Fa,MnPrv,TenC,2000,7,2006,WD,Normal,250000
1423,1424,80,RL,NaN,19690,Pave,NaN,IR1,Lvl,AllPub,...,738,Gd,GdPrv,NaN,0,8,2006,WD,Alloca,274970

In [250]:
# add 'PricePerSqM' column to df
housing_df['PricePerSqM'] = housing_df.SalePrice / housing_df.LotArea

housing_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PricePerSqM
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,24.674556
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,18.906250
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,19.866667
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,14.659686
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,17.531557

In [251]:
# describe data of PricePerSqM column
housing_df.PricePerSqM.describe()

count    1460.000000
mean       21.069878
            ...
75%        23.769031
max        95.384615
Name: PricePerSqM, Length: 8, dtype: float64

In [252]:
# check only mean value of PricePerSqM
housing_df.PricePerSqM.mean()

np.float64(21.06987836020315)

In [253]:
# check unique values and number
unv = housing_df.PricePerSqM.unique()
unv, unv.size

(array([24.67455621, 18.90625   , 19.86666667, ..., 29.47356779,
        14.62642791, 14.84351414]),
 1434)

In [254]:
# unique values and how often they occur
housing_df.PricePerSqM.value_counts()

PricePerSqM
16.666667    3
12.500000    3
            ..
17.079144    1
14.843514    1
Name: count, Length: 1434, dtype: int64

In [255]:
# check the PricePerSqM delta from mean value (remean), also map() or apply() can be used
PricePerSqM_mean = housing_df.PricePerSqM.mean()
housing_df.PricePerSqM - PricePerSqM_mean

0       3.604678
1      -2.163628
          ...
1458   -6.443450
1459   -6.226364
Name: PricePerSqM, Length: 1460, dtype: float64

In [256]:
# get the most expensive house in every SaleCondition
housing_df.groupby('SaleCondition').SalePrice.max()

SaleCondition
Abnorml    745000
AdjLand    127500
            ...
Normal     755000
Partial    611657
Name: SalePrice, Length: 6, dtype: int64

In [257]:
# get the first house in the df of every SaleCondition
housing_df.groupby('SaleCondition').apply(lambda df: df.iloc[0])

/var/folders/t0/vsn_5y754hl6h7fxjm_9bvr40000gn/T/ipykernel_36847/571179002.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  housing_df.groupby('SaleCondition').apply(lambda df: df.iloc[0])

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PricePerSqM
SaleCondition,,,,,,,,,,,,,,,,,,,,,
Abnorml,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,14.659686
AdjLand,40,90,RL,65.0,6040,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2008,WD,AdjLand,82000,13.576159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Normal,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,24.674556
Partial,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2006,New,Partial,345000,28.933244

In [258]:
# SalePrice statistics by SaleCondition
housing_df.groupby(['SaleCondition']).SalePrice.agg([len, min, max])

/var/folders/t0/vsn_5y754hl6h7fxjm_9bvr40000gn/T/ipykernel_36847/576410792.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  housing_df.groupby(['SaleCondition']).SalePrice.agg([len, min, max])
/var/folders/t0/vsn_5y754hl6h7fxjm_9bvr40000gn/T/ipykernel_36847/576410792.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  housing_df.groupby(['SaleCondition']).SalePrice.agg([len, min, max])

                len     min     max
SaleCondition
Abnorml         101   34900  745000
AdjLand           4   81000  127500
...             ...     ...     ...
Normal         1198   39300  755000
Partial         125  113000  611657

[6 rows x 3 columns]

In [259]:
# multi-indexes
sc_y_indexed = housing_df.groupby(['SaleCondition', 'YearBuilt']).SalePrice.agg([len])
sc_y_indexed

                         len
SaleCondition YearBuilt
Abnorml       1880         1
              1900         2
...                      ...
Partial       2009        15
              2010         1

[210 rows x 1 columns]

In [260]:
# get back to regular indexing
sc_y_indexed.reset_index()

    SaleCondition  YearBuilt  len
0         Abnorml       1880    1
1         Abnorml       1900    2
..            ...        ...  ...
208       Partial       2009   15
209       Partial       2010    1

[210 rows x 3 columns]

In [261]:
# sort by len
sc_y_indexed.sort_values(by='len')

                         len
SaleCondition YearBuilt
Abnorml       1880         1
Family        1954         1
...                      ...
Normal        2003        43
              2004        52

[210 rows x 1 columns]

In [262]:
# desc order
sc_y_indexed.sort_values(by='len', ascending=False)

                         len
SaleCondition YearBuilt
Normal        2004        52
              2003        43
...                      ...
Family        1954         1
Partial       2010         1

[210 rows x 1 columns]

In [263]:
# sort by index
sc_y_indexed = sc_y_indexed.reset_index()
sc_y_indexed.sort_index()

    SaleCondition  YearBuilt  len
0         Abnorml       1880    1
1         Abnorml       1900    2
..            ...        ...  ...
208       Partial       2009   15
209       Partial       2010    1

[210 rows x 3 columns]

In [264]:
# sortby several columns
sc_y_indexed.sort_values(by=['len', 'YearBuilt'], ascending=False)

    SaleCondition  YearBuilt  len
194        Normal       2004   52
193        Normal       2003   43
..            ...        ...  ...
91         Normal       1875    1
90         Normal       1872    1

[210 rows x 3 columns]

In [265]:
# check column data type
housing_df.Utilities.dtype

dtype('O')

In [266]:
# check all columns data type
housing_df.dtypes

Id               int64
MSSubClass       int64
                ...
SalePrice        int64
PricePerSqM    float64
Length: 82, dtype: object

In [267]:
# convert column type
housing_df.PricePerSqM.astype('int64')

0       24
1       18
        ..
1458    14
1459    14
Name: PricePerSqM, Length: 1460, dtype: int64

In [268]:
# select houses without pool
housing_df.loc[pd.isnull(housing_df.PoolQC)]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PricePerSqM
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,24.674556
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,18.906250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2010,WD,Normal,142125,14.626428
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2008,WD,Normal,147500,14.843514

In [269]:
# fill NaN with some value
housing_df.PoolQC = housing_df.PoolQC.fillna("No Pool")
housing_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PricePerSqM
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,No Pool,NaN,NaN,0,2,2008,WD,Normal,208500,24.674556
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,No Pool,NaN,NaN,0,5,2007,WD,Normal,181500,18.906250
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,No Pool,NaN,NaN,0,9,2008,WD,Normal,223500,19.866667
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,No Pool,NaN,NaN,0,2,2006,WD,Abnorml,140000,14.659686
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,No Pool,NaN,NaN,0,12,2008,WD,Normal,250000,17.531557

In [270]:
# replace some values with another
housing_df.LotShape = housing_df.LotShape.replace("Reg", "regtangle")
housing_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PricePerSqM
0,1,60,RL,65.0,8450,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,2,2008,WD,Normal,208500,24.674556
1,2,20,RL,80.0,9600,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,5,2007,WD,Normal,181500,18.906250
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,No Pool,NaN,NaN,0,9,2008,WD,Normal,223500,19.866667
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,No Pool,NaN,NaN,0,2,2006,WD,Abnorml,140000,14.659686
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,No Pool,NaN,NaN,0,12,2008,WD,Normal,250000,17.531557

In [271]:
# renaming column
housing_df.rename(columns={'SalePrice': 'Price'})

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,Price,PricePerSqM
0,1,60,RL,65.0,8450,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,2,2008,WD,Normal,208500,24.674556
1,2,20,RL,80.0,9600,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,5,2007,WD,Normal,181500,18.906250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,1459,20,RL,68.0,9717,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,4,2010,WD,Normal,142125,14.626428
1459,1460,20,RL,75.0,9937,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,6,2008,WD,Normal,147500,14.843514

In [272]:
# rename index (manual alternative to set_index())
housing_df.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PricePerSqM
firstEntry,1,60,RL,65.0,8450,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,2,2008,WD,Normal,208500,24.674556
secondEntry,2,20,RL,80.0,9600,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,5,2007,WD,Normal,181500,18.906250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,1459,20,RL,68.0,9717,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,4,2010,WD,Normal,142125,14.626428
1459,1460,20,RL,75.0,9937,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,6,2008,WD,Normal,147500,14.843514

In [273]:
# change row and column names
housing_df.rename_axis("test0", axis='rows').rename_axis("test", axis='columns')

test,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PricePerSqM
test0,,,,,,,,,,,,,,,,,,,,,
0,1,60,RL,65.0,8450,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,2,2008,WD,Normal,208500,24.674556
1,2,20,RL,80.0,9600,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,5,2007,WD,Normal,181500,18.906250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,1459,20,RL,68.0,9717,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,4,2010,WD,Normal,142125,14.626428
1459,1460,20,RL,75.0,9937,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,6,2008,WD,Normal,147500,14.843514

In [274]:
# combining data vertically
test_file_path = '../external-data/test.csv'
housing_df1 = pd.read_csv(test_file_path)

pd.concat([housing_df, housing_df1])

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PricePerSqM
0,1,60,RL,65.0,8450,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,2,2008,WD,Normal,208500.0,24.674556
1,2,20,RL,80.0,9600,Pave,NaN,regtangle,Lvl,AllPub,...,No Pool,NaN,NaN,0,5,2007,WD,Normal,181500.0,18.906250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN,NaN
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN,NaN

In [275]:
# combine data horizontaly (join)
left = housing_df.set_index(['Id', 'LotArea'])
right = housing_df1.set_index(['Id', 'LotArea'])

left.join(right, lsuffix='_train', rsuffix='_test')

,,MSSubClass_train,MSZoning_train,LotFrontage_train,Street_train,Alley_train,LotShape_train,LandContour_train,Utilities_train,LotConfig_train,LandSlope_train,...,ScreenPorch_test,PoolArea_test,PoolQC_test,Fence_test,MiscFeature_test,MiscVal_test,MoSold_test,YrSold_test,SaleType_test,SaleCondition_test
Id,LotArea,,,,,,,,,,,,,,,,,,,,,
1,8450,60,RL,65.0,Pave,NaN,regtangle,Lvl,AllPub,Inside,Gtl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9600,20,RL,80.0,Pave,NaN,regtangle,Lvl,AllPub,FR2,Gtl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,9717,20,RL,68.0,Pave,NaN,regtangle,Lvl,AllPub,Inside,Gtl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1460,9937,20,RL,75.0,Pave,NaN,regtangle,Lvl,AllPub,Inside,Gtl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN